# Autogenerated wrapper script for pthread_win32_jll for i686-w64-mingw32
export pthread

JLLWrappers.@generate_wrapper_header("pthread_win32")
JLLWrappers.@declare_library_product(pthread, "pthreadGC3.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        pthread,
        "bin\\pthreadGC3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
